# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
    - main
    - gh-readonly-queue/main/**
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Mask sensitive
      run: |
          echo "::add-mask::${{ secrets.NTROPY_API_KEY }}"
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.15
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scikit-learn pandas requests_toolbelt pydantic
        pip install -e .[benchmark]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --ignore=F541,E501,E226,E251,E203,F401,F841,C901,W503 --count --max-complexity=10 --max-line-length=160 --statistics
    - name: Test with pytest
      run: |
        pytest
      env:
        NTROPY_API_KEY: ${{ secrets.NTROPY_API_KEY }}
